const initSqlJs = require("sql.js");
const fs = require("fs");
const path = require("path");

const DB_PATH = path.join(__dirname, "doctors.db");

async function setup() {
  const SQL = await initSqlJs();
  const db = new SQL.Database();

  db.run(`
    CREATE TABLE doctors (
      id               INTEGER PRIMARY KEY AUTOINCREMENT,
      name             TEXT    NOT NULL,
      specialty        TEXT    NOT NULL,
      experience       INTEGER NOT NULL,
      city             TEXT    NOT NULL,
      hospital         TEXT    NOT NULL,
      phone            TEXT    NOT NULL,
      email            TEXT    NOT NULL,
      rating           REAL    DEFAULT 0,
      consultation_fee INTEGER DEFAULT 0,
      availability     TEXT    DEFAULT 'Mon-Fri',
      gender           TEXT    DEFAULT 'Male',
      bio              TEXT    DEFAULT '',
      image            TEXT    DEFAULT '',
      created_at       DATETIME DEFAULT CURRENT_TIMESTAMP
    );
  `);

  const doctors = [
    // ── Cardiologists ───────────────────────────────────────
    {
      name: "Dr. Rajesh Sharma",
      specialty: "Cardiologist",
      experience: 18,
      city: "New Delhi",
      hospital: "All India Institute of Medical Sciences (AIIMS)",
      phone: "+91-98100-12345",
      email: "rajesh.sharma@aiims.edu",
      rating: 4.9,
      fee: 1500,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Senior interventional cardiologist at AIIMS with expertise in complex angioplasty and heart valve repair procedures.",
    },
    {
      name: "Dr. Priya Menon",
      specialty: "Cardiologist",
      experience: 14,
      city: "Mumbai",
      hospital: "Kokilaben Dhirubhai Ambani Hospital",
      phone: "+91-98200-23456",
      email: "priya.menon@kokilaben.com",
      rating: 4.8,
      fee: 2000,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Leading female cardiologist in Mumbai specializing in women's heart health and preventive cardiology.",
    },
    {
      name: "Dr. Suresh Nair",
      specialty: "Cardiologist",
      experience: 22,
      city: "Chennai",
      hospital: "Apollo Hospitals Greams Road",
      phone: "+91-98400-34567",
      email: "suresh.nair@apollohospitals.com",
      rating: 4.7,
      fee: 1200,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Pioneer in minimally invasive cardiac surgery with over two decades of experience in bypass surgery.",
    },
    {
      name: "Dr. Ananya Chatterjee",
      specialty: "Cardiologist",
      experience: 10,
      city: "Kolkata",
      hospital: "Fortis Hospital Anandapur",
      phone: "+91-98300-45678",
      email: "ananya.chatterjee@fortis.com",
      rating: 4.6,
      fee: 1000,
      avail: "Mon-Thu",
      gender: "Female",
      bio: "Young cardiologist specializing in cardiac imaging, echocardiography, and congenital heart disease.",
    },
    {
      name: "Dr. Vikram Singh Rathore",
      specialty: "Cardiologist",
      experience: 25,
      city: "Jaipur",
      hospital: "Eternal Heart Care Centre",
      phone: "+91-98290-56789",
      email: "vikram.rathore@eternalheart.in",
      rating: 4.9,
      fee: 800,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Rajasthan's most experienced cardiologist with 25+ years and over 10,000 successful angioplasties.",
    },

    // ── Dermatologists ──────────────────────────────────────
    {
      name: "Dr. Kavita Reddy",
      specialty: "Dermatologist",
      experience: 12,
      city: "Hyderabad",
      hospital: "Yashoda Hospitals Somajiguda",
      phone: "+91-99490-67890",
      email: "kavita.reddy@yashoda.org",
      rating: 4.7,
      fee: 800,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Board-certified dermatologist with expertise in laser treatments, vitiligo management, and cosmetic procedures.",
    },
    {
      name: "Dr. Arjun Kapoor",
      specialty: "Dermatologist",
      experience: 9,
      city: "Bangalore",
      hospital: "Manipal Hospital Old Airport Road",
      phone: "+91-98450-78901",
      email: "arjun.kapoor@manipal.edu",
      rating: 4.5,
      fee: 1000,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Specialist in acne scarring, hair transplant procedures, and advanced skin rejuvenation therapies.",
    },
    {
      name: "Dr. Sneha Deshmukh",
      specialty: "Dermatologist",
      experience: 15,
      city: "Pune",
      hospital: "Ruby Hall Clinic",
      phone: "+91-98220-89012",
      email: "sneha.deshmukh@rubyhall.com",
      rating: 4.8,
      fee: 700,
      avail: "Mon-Wed, Sat",
      gender: "Female",
      bio: "Expert in psoriasis treatment, eczema care, and pediatric dermatology with 15 years of practice.",
    },
    {
      name: "Dr. Rohit Gupta",
      specialty: "Dermatologist",
      experience: 7,
      city: "New Delhi",
      hospital: "Max Super Speciality Hospital Saket",
      phone: "+91-98110-90123",
      email: "rohit.gupta@maxhealthcare.com",
      rating: 4.4,
      fee: 1200,
      avail: "Mon-Fri",
      gender: "Male",
      bio: "Young dermatologist focused on skin cancer screening, mole mapping, and cosmetic dermatology.",
    },

    // ── Neurologists ────────────────────────────────────────
    {
      name: "Dr. Meera Iyer",
      specialty: "Neurologist",
      experience: 16,
      city: "Bangalore",
      hospital:
        "NIMHANS (National Institute of Mental Health and Neurosciences)",
      phone: "+91-98860-01234",
      email: "meera.iyer@nimhans.ac.in",
      rating: 4.9,
      fee: 1500,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Leading neurologist at India's premier neuroscience institute, specializing in epilepsy and stroke management.",
    },
    {
      name: "Dr. Amit Verma",
      specialty: "Neurologist",
      experience: 20,
      city: "Mumbai",
      hospital: "Nanavati Max Super Speciality Hospital",
      phone: "+91-98190-12345",
      email: "amit.verma@nanavati.org",
      rating: 4.8,
      fee: 2000,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Expert in neurodegenerative diseases, Parkinson's treatment, and deep brain stimulation therapy.",
    },
    {
      name: "Dr. Lakshmi Sundaram",
      specialty: "Neurologist",
      experience: 11,
      city: "Chennai",
      hospital: "SIMS Hospital Vadapalani",
      phone: "+91-98410-23456",
      email: "lakshmi.sundaram@simshospital.com",
      rating: 4.6,
      fee: 900,
      avail: "Mon-Thu",
      gender: "Female",
      bio: "Specializes in pediatric neurology, headache disorders, and autoimmune neurological conditions.",
    },

    // ── Orthopedic Surgeons ─────────────────────────────────
    {
      name: "Dr. Sanjay Desai",
      specialty: "Orthopedic Surgeon",
      experience: 24,
      city: "Mumbai",
      hospital: "Hinduja Hospital Mahim",
      phone: "+91-98200-34567",
      email: "sanjay.desai@hinduja.com",
      rating: 4.9,
      fee: 1800,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "India's leading joint replacement surgeon with 24 years and over 8,000 knee and hip replacements.",
    },
    {
      name: "Dr. Pooja Bhatia",
      specialty: "Orthopedic Surgeon",
      experience: 13,
      city: "New Delhi",
      hospital: "Indian Spinal Injuries Centre Vasant Kunj",
      phone: "+91-98100-45678",
      email: "pooja.bhatia@isic.in",
      rating: 4.7,
      fee: 1500,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Spine surgery specialist with expertise in scoliosis correction and minimally invasive disc surgery.",
    },
    {
      name: "Dr. Manoj Kumar",
      specialty: "Orthopedic Surgeon",
      experience: 17,
      city: "Lucknow",
      hospital: "King George's Medical University Hospital",
      phone: "+91-94150-56789",
      email: "manoj.kumar@kgmu.org",
      rating: 4.5,
      fee: 600,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Expert in sports medicine, arthroscopic surgery, and fracture management at UP's premier medical university.",
    },
    {
      name: "Dr. Harpreet Kaur",
      specialty: "Orthopedic Surgeon",
      experience: 8,
      city: "Chandigarh",
      hospital:
        "PGIMER (Post Graduate Institute of Medical Education and Research)",
      phone: "+91-98140-67890",
      email: "harpreet.kaur@pgimer.edu.in",
      rating: 4.6,
      fee: 500,
      avail: "Mon-Thu",
      gender: "Female",
      bio: "Pediatric orthopedic specialist focused on limb deformity correction and congenital bone disorders.",
    },

    // ── Pediatricians ───────────────────────────────────────
    {
      name: "Dr. Deepa Krishnan",
      specialty: "Pediatrician",
      experience: 19,
      city: "Kochi",
      hospital: "Amrita Institute of Medical Sciences",
      phone: "+91-98470-78901",
      email: "deepa.krishnan@amrita.edu",
      rating: 4.8,
      fee: 700,
      avail: "Mon-Sat",
      gender: "Female",
      bio: "Kerala's most trusted pediatrician with special interest in neonatal care and childhood nutrition.",
    },
    {
      name: "Dr. Ravi Shankar",
      specialty: "Pediatrician",
      experience: 14,
      city: "Bangalore",
      hospital: "Cloudnine Hospital Jayanagar",
      phone: "+91-98800-89012",
      email: "ravi.shankar@cloudnine.in",
      rating: 4.7,
      fee: 1000,
      avail: "Mon-Fri",
      gender: "Male",
      bio: "Expert in childhood vaccinations, growth disorders, and adolescent health management.",
    },
    {
      name: "Dr. Nisha Agarwal",
      specialty: "Pediatrician",
      experience: 6,
      city: "Jaipur",
      hospital: "Narayana Multispeciality Hospital",
      phone: "+91-98280-90123",
      email: "nisha.agarwal@narayana.in",
      rating: 4.4,
      fee: 500,
      avail: "Mon-Sat",
      gender: "Female",
      bio: "Young pediatrician passionate about preventive childcare and developmental milestone tracking.",
    },
    {
      name: "Dr. Arun Prakash",
      specialty: "Pediatrician",
      experience: 21,
      city: "Chennai",
      hospital: "Kanchi Kamakoti CHILDS Trust Hospital",
      phone: "+91-98400-01234",
      email: "arun.prakash@childstrust.in",
      rating: 4.9,
      fee: 600,
      avail: "Mon-Fri",
      gender: "Male",
      bio: "Two decades of experience in pediatric emergency medicine and childhood infectious diseases.",
    },

    // ── Gynecologists ───────────────────────────────────────
    {
      name: "Dr. Swati Pillai",
      specialty: "Gynecologist",
      experience: 16,
      city: "Mumbai",
      hospital: "Breach Candy Hospital",
      phone: "+91-98210-12345",
      email: "swati.pillai@breachcandy.org",
      rating: 4.8,
      fee: 2000,
      avail: "Mon-Sat",
      gender: "Female",
      bio: "High-risk pregnancy specialist with expertise in laparoscopic gynecological surgery.",
    },
    {
      name: "Dr. Rekha Devi",
      specialty: "Gynecologist",
      experience: 22,
      city: "New Delhi",
      hospital: "Safdarjung Hospital",
      phone: "+91-98110-23456",
      email: "rekha.devi@safdarjung.nic.in",
      rating: 4.7,
      fee: 800,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Senior gynecologist with extensive experience in maternal health, family planning, and infertility treatment.",
    },
    {
      name: "Dr. Anjali Patil",
      specialty: "Gynecologist",
      experience: 11,
      city: "Pune",
      hospital: "Jehangir Hospital",
      phone: "+91-98230-34567",
      email: "anjali.patil@jehangir.com",
      rating: 4.6,
      fee: 1000,
      avail: "Mon-Thu",
      gender: "Female",
      bio: "IVF specialist and reproductive endocrinologist helping couples with fertility treatments.",
    },

    // ── ENT Specialists ─────────────────────────────────────
    {
      name: "Dr. Karthik Raman",
      specialty: "ENT Specialist",
      experience: 13,
      city: "Chennai",
      hospital: "Sri Ramachandra Medical Centre",
      phone: "+91-98400-45678",
      email: "karthik.raman@srmc.edu",
      rating: 4.7,
      fee: 800,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "ENT surgeon with expertise in cochlear implants, endoscopic sinus surgery, and voice disorders.",
    },
    {
      name: "Dr. Neha Joshi",
      specialty: "ENT Specialist",
      experience: 8,
      city: "Ahmedabad",
      hospital: "Sterling Hospital Drive-In Road",
      phone: "+91-98250-56789",
      email: "neha.joshi@sterling.in",
      rating: 4.5,
      fee: 600,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Specialist in pediatric ENT, sleep apnea treatment, and allergy management.",
    },
    {
      name: "Dr. Vinod Mathew",
      specialty: "ENT Specialist",
      experience: 19,
      city: "Thiruvananthapuram",
      hospital: "KIMS Hospital",
      phone: "+91-98950-67890",
      email: "vinod.mathew@kimsglobal.com",
      rating: 4.8,
      fee: 700,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Pioneer in skull base surgery and head-neck oncology with national recognition.",
    },

    // ── General Physicians ──────────────────────────────────
    {
      name: "Dr. Ramesh Chandra",
      specialty: "General Physician",
      experience: 28,
      city: "Varanasi",
      hospital: "BHU Sir Sunderlal Hospital",
      phone: "+91-94150-78901",
      email: "ramesh.chandra@bhu.ac.in",
      rating: 4.7,
      fee: 300,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Veteran physician with nearly three decades serving the people of eastern UP through affordable healthcare.",
    },
    {
      name: "Dr. Divya Narayan",
      specialty: "General Physician",
      experience: 10,
      city: "Bangalore",
      hospital: "Sakra World Hospital",
      phone: "+91-98860-89012",
      email: "divya.narayan@sakraworldhospital.com",
      rating: 4.5,
      fee: 800,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Internal medicine specialist focused on lifestyle diseases, diabetes management, and executive health checkups.",
    },
    {
      name: "Dr. Ashok Mehta",
      specialty: "General Physician",
      experience: 15,
      city: "Ahmedabad",
      hospital: "Civil Hospital Ahmedabad",
      phone: "+91-98240-90123",
      email: "ashok.mehta@civilhospital.org",
      rating: 4.3,
      fee: 400,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Dedicated public health physician serving thousands of patients daily at Gujarat's largest government hospital.",
    },

    // ── Psychiatrists ───────────────────────────────────────
    {
      name: "Dr. Simran Bedi",
      specialty: "Psychiatrist",
      experience: 12,
      city: "New Delhi",
      hospital: "IHBAS (Institute of Human Behaviour and Allied Sciences)",
      phone: "+91-98110-01234",
      email: "simran.bedi@ihbas.org",
      rating: 4.8,
      fee: 1500,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Clinical psychiatrist specializing in anxiety disorders, OCD, bipolar disorder, and PTSD therapy.",
    },
    {
      name: "Dr. Venkatesh Rao",
      specialty: "Psychiatrist",
      experience: 20,
      city: "Bangalore",
      hospital: "NIMHANS",
      phone: "+91-98860-12345",
      email: "venkatesh.rao@nimhans.ac.in",
      rating: 4.9,
      fee: 1200,
      avail: "Mon-Thu",
      gender: "Male",
      bio: "Senior psychiatrist at India's top mental health institute, expert in addiction medicine and schizophrenia treatment.",
    },

    // ── Urologists ──────────────────────────────────────────
    {
      name: "Dr. Pankaj Maheshwari",
      specialty: "Urologist",
      experience: 17,
      city: "Mumbai",
      hospital: "Lilavati Hospital Bandra",
      phone: "+91-98200-23456",
      email: "pankaj.maheshwari@lilavati.com",
      rating: 4.8,
      fee: 1800,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Renowned urologist specializing in robotic prostatectomy, kidney transplant, and laser stone treatment.",
    },
    {
      name: "Dr. Shweta Kumari",
      specialty: "Urologist",
      experience: 9,
      city: "Patna",
      hospital: "Indira Gandhi Institute of Medical Sciences",
      phone: "+91-98350-34567",
      email: "shweta.kumari@igims.org",
      rating: 4.5,
      fee: 500,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "One of Bihar's few female urologists, focused on female urology and urinary incontinence treatment.",
    },

    // ── Ophthalmologists ────────────────────────────────────
    {
      name: "Dr. Aditya Jain",
      specialty: "Ophthalmologist",
      experience: 15,
      city: "New Delhi",
      hospital: "Dr. Shroff's Charity Eye Hospital",
      phone: "+91-98100-45678",
      email: "aditya.jain@sceh.net",
      rating: 4.9,
      fee: 1000,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Expert in LASIK, cataract microsurgery, and corneal transplantation at Delhi's oldest eye hospital.",
    },
    {
      name: "Dr. Padmini Gopalan",
      specialty: "Ophthalmologist",
      experience: 18,
      city: "Madurai",
      hospital: "Aravind Eye Hospital",
      phone: "+91-98420-56789",
      email: "padmini.gopalan@aravind.org",
      rating: 4.8,
      fee: 400,
      avail: "Mon-Sat",
      gender: "Female",
      bio: "Retinal surgeon at the world-famous Aravind Eye Care System, serving thousands of underprivileged patients.",
    },

    // ── Dentists ────────────────────────────────────────────
    {
      name: "Dr. Tanvi Shah",
      specialty: "Dentist",
      experience: 6,
      city: "Mumbai",
      hospital: "Nair Hospital Dental College",
      phone: "+91-98190-67890",
      email: "tanvi.shah@nairhosp.org",
      rating: 4.4,
      fee: 500,
      avail: "Mon-Sat",
      gender: "Female",
      bio: "Skilled in cosmetic dentistry, smile makeovers, root canal therapy, and dental implant procedures.",
    },
    {
      name: "Dr. Gaurav Mishra",
      specialty: "Dentist",
      experience: 14,
      city: "Lucknow",
      hospital: "Charak Hospital and Research Centre",
      phone: "+91-94150-78901",
      email: "gaurav.mishra@charak.in",
      rating: 4.7,
      fee: 400,
      avail: "Mon-Fri",
      gender: "Male",
      bio: "Expert in orthodontics, invisible braces, and full mouth rehabilitation with 14 years of practice.",
    },
    {
      name: "Dr. Ishita Das",
      specialty: "Dentist",
      experience: 4,
      city: "Guwahati",
      hospital: "Gauhati Medical College Hospital",
      phone: "+91-97060-89012",
      email: "ishita.das@gmch.org",
      rating: 4.2,
      fee: 300,
      avail: "Mon-Wed, Sat",
      gender: "Female",
      bio: "Young dentist passionate about preventive oral health, pediatric dentistry, and community dental camps.",
    },

    // ── Oncologists ─────────────────────────────────────────
    {
      name: "Dr. Sunil Rawal",
      specialty: "Oncologist",
      experience: 26,
      city: "Mumbai",
      hospital: "Tata Memorial Hospital",
      phone: "+91-98200-90123",
      email: "sunil.rawal@tmc.gov.in",
      rating: 4.9,
      fee: 2500,
      avail: "Mon-Fri",
      gender: "Male",
      bio: "Head of surgical oncology at Asia's premier cancer centre with 26 years of cancer treatment expertise.",
    },
    {
      name: "Dr. Gayatri Sethi",
      specialty: "Oncologist",
      experience: 13,
      city: "Kolkata",
      hospital: "Tata Medical Center Rajarhat",
      phone: "+91-98300-01234",
      email: "gayatri.sethi@tmckolkata.com",
      rating: 4.7,
      fee: 1500,
      avail: "Mon-Thu",
      gender: "Female",
      bio: "Medical oncologist specializing in breast cancer, lymphoma, and targeted immunotherapy treatments.",
    },

    // ── Pulmonologists ──────────────────────────────────────
    {
      name: "Dr. Mohammad Irfan",
      specialty: "Pulmonologist",
      experience: 14,
      city: "Hyderabad",
      hospital: "Krishna Institute of Medical Sciences",
      phone: "+91-99490-12345",
      email: "mohammad.irfan@kimshospitals.com",
      rating: 4.6,
      fee: 800,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Expert in asthma, COPD, interstitial lung disease, and critical care pulmonology.",
    },
    {
      name: "Dr. Sunita Yadav",
      specialty: "Pulmonologist",
      experience: 9,
      city: "New Delhi",
      hospital: "Vallabhbhai Patel Chest Institute",
      phone: "+91-98110-23456",
      email: "sunita.yadav@vpci.du.ac.in",
      rating: 4.5,
      fee: 1000,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Tuberculosis and respiratory infection specialist at Delhi's dedicated chest disease centre.",
    },

    // ── Endocrinologists ────────────────────────────────────
    {
      name: "Dr. Nikhil Tandon",
      specialty: "Endocrinologist",
      experience: 23,
      city: "New Delhi",
      hospital: "AIIMS New Delhi",
      phone: "+91-98100-34567",
      email: "nikhil.tandon@aiims.edu",
      rating: 4.9,
      fee: 1500,
      avail: "Mon-Fri",
      gender: "Male",
      bio: "India's foremost endocrinologist and diabetes researcher, leading national diabetes prevention programs.",
    },
    {
      name: "Dr. Pallavi Sinha",
      specialty: "Endocrinologist",
      experience: 8,
      city: "Bangalore",
      hospital: "Narayana Health City",
      phone: "+91-98860-45678",
      email: "pallavi.sinha@narayanahealth.org",
      rating: 4.5,
      fee: 900,
      avail: "Mon-Wed, Sat",
      gender: "Female",
      bio: "Thyroid disorder specialist with focus on PCOS management and metabolic syndrome treatment.",
    },

    // ── Gastroenterologists ─────────────────────────────────
    {
      name: "Dr. Abhay Kumar",
      specialty: "Gastroenterologist",
      experience: 19,
      city: "Hyderabad",
      hospital: "Asian Institute of Gastroenterology",
      phone: "+91-99490-56789",
      email: "abhay.kumar@aigindia.com",
      rating: 4.8,
      fee: 1200,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Expert in advanced endoscopy, ERCP, liver transplant evaluation, and inflammatory bowel disease.",
    },
    {
      name: "Dr. Rina Banerjee",
      specialty: "Gastroenterologist",
      experience: 11,
      city: "Kolkata",
      hospital: "AMRI Hospital Dhakuria",
      phone: "+91-98310-67890",
      email: "rina.banerjee@amrihospitals.in",
      rating: 4.6,
      fee: 800,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Hepatologist specializing in Hepatitis B/C treatment, fatty liver disease, and gastrointestinal cancers.",
    },

    // ── Nephrologists ───────────────────────────────────────
    {
      name: "Dr. Sandeep Guleria",
      specialty: "Nephrologist",
      experience: 21,
      city: "New Delhi",
      hospital: "Sir Ganga Ram Hospital",
      phone: "+91-98100-78901",
      email: "sandeep.guleria@sgrh.com",
      rating: 4.9,
      fee: 1500,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "Leading kidney transplant surgeon with over 2,000 successful transplants and dialysis access procedures.",
    },
    {
      name: "Dr. Aparna Hegde",
      specialty: "Nephrologist",
      experience: 10,
      city: "Pune",
      hospital: "Sahyadri Super Speciality Hospital",
      phone: "+91-98230-89012",
      email: "aparna.hegde@sahyadri.in",
      rating: 4.5,
      fee: 800,
      avail: "Mon-Thu",
      gender: "Female",
      bio: "Focused on chronic kidney disease prevention, pediatric nephrology, and peritoneal dialysis management.",
    },

    // ── Ayurveda (Bonus - Indian specialty) ─────────────────
    {
      name: "Dr. Raghavendra Prasad",
      specialty: "Ayurveda Specialist",
      experience: 30,
      city: "Mysuru",
      hospital: "JSS Ayurveda Hospital",
      phone: "+91-98860-90123",
      email: "raghavendra.prasad@jssuni.edu.in",
      rating: 4.8,
      fee: 500,
      avail: "Mon-Sat",
      gender: "Male",
      bio: "30 years of Ayurvedic practice specializing in Panchakarma therapy, chronic pain management, and holistic healing.",
    },
    {
      name: "Dr. Vasundhara Devi",
      specialty: "Ayurveda Specialist",
      experience: 18,
      city: "Jaipur",
      hospital: "National Institute of Ayurveda",
      phone: "+91-98290-01234",
      email: "vasundhara.devi@nia.nic.in",
      rating: 4.7,
      fee: 400,
      avail: "Mon-Fri",
      gender: "Female",
      bio: "Expert in women's health through Ayurveda, herbal medicine, and traditional Rajasthani healing practices.",
    },
  ];

  const stmt = db.prepare(`
    INSERT INTO doctors (name, specialty, experience, city, hospital,
                         phone, email, rating, consultation_fee,
                         availability, gender, bio, image)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  for (const d of doctors) {
    const bgColor = d.gender === "Female" ? "7C3AED" : "0D6EFD";
    const imgName = encodeURIComponent(d.name.replace("Dr. ", ""));
    const image = `https://ui-avatars.com/api/?name=${imgName}&background=${bgColor}&color=fff&size=200&bold=true&font-size=0.4`;

    stmt.run([
      d.name,
      d.specialty,
      d.experience,
      d.city,
      d.hospital,
      d.phone,
      d.email,
      d.rating,
      d.fee,
      d.avail,
      d.gender,
      d.bio,
      image,
    ]);
  }

  stmt.free();

  const data = db.export();
  fs.writeFileSync(DB_PATH, Buffer.from(data));

  console.log(`✅ Database seeded with ${doctors.length} doctors → ${DB_PATH}`);
  db.close();
}

setup().catch(console.error);
